version: '3'

services:
  db_mysql:
    container_name: 'database'
    image: 'mysql:8.0'
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - "./database:/var/lib/mysql"
